services:
  landing-service:
    build:
      context: ./services/landing-service
    container_name: resourcehive-landing
    ports:
      - "8080:80"
    volumes:
      - ./services/landing-service:/usr/share/nginx/html