packages:
  - "apps/*"
  - "services/*"
  - "packages/*"

allowBuilds:
  '0': '@prisma/client'
  '1': '@prisma/engines'
  '2': prisma
  '3': unrs-resolver
  '@prisma/client': true
  '@prisma/engines': true
  'bcrypt': true
  prisma: true
  sharp: true
  unrs-resolver: true
