worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    
    sendfile        on;
    keepalive_timeout  65;

    # Upstream services
    upstream identity_service {
        server identity-service:3000; 
    }

    server {
        listen 80;
        server_name localhost;
        
        # user cannot access only nginx can access this
        location = /_auth_validate {
            internal;
            proxy_pass http://identity_service/auth/validate;
            
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header X-Original-URI $request_uri;
            
            # Pass original Authorization header. Then identity-service can read the JWT
            proxy_set_header Authorization $http_authorization;
        }

        # Public login endpoint.
        location /auth/ {
            proxy_pass http://identity_service/auth/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
