name: Deploy ResourceHive

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd ~/resourcehive

            git fetch origin

            git reset --hard origin/dev

            docker compose -f docker-compose.prod.yml down || true

            docker compose -f docker-compose.prod.yml up --build -d